//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OssBssSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Contract = new HashSet<Contract>();
            this.Requests = new HashSet<Requests>();
        }
    
        public string ID { get; set; }
        public string FullName { get; set; }
        public byte GenderID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string TelNumber { get; set; }
        public string Email { get; set; }
        public string ResindaceAddress { get; set; }
        public string AddressCode { get; set; }
        public Nullable<int> AddressRaion { get; set; }
        public string AddressPrefix { get; set; }
        public string AddressHouse { get; set; }
        public string Pasport { get; set; }
        public string Code { get; set; }
        public string PasportPlace { get; set; }
        public Nullable<System.DateTime> PasportDate { get; set; }
        public string LicevoySchet { get; set; }
    
        public virtual AddressRaions AddressRaions { get; set; }
        public virtual Genders Genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
