//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OssBssSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Contract_Service = new HashSet<Contract_Service>();
        }
    
        public int ID { get; set; }
        public string ClientID { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ContractTypeID { get; set; }
        public string ReasonOfEnd { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Addition { get; set; }
        public string EquipmentID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ContractTypes ContractTypes { get; set; }
        public virtual Equipments Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Service> Contract_Service { get; set; }
    }
}
