//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OssBssSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Service
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public int ServiceTypeID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
