//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OssBssSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public System.DateTime StartDate { get; set; }
        public string ClientID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public Nullable<int> ServiceKindID { get; set; }
        public Nullable<int> ServiceConnectTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProblemTypeID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual ProblemTypes ProblemTypes { get; set; }
        public virtual RequestStatuses RequestStatuses { get; set; }
        public virtual ServiceConnectTypes ServiceConnectTypes { get; set; }
        public virtual ServiceKinds ServiceKinds { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
